export const ALL_PROFILE_REQUEST = 'ALL_PROFILE_REQUEST'
export const ALL_PROFILE_SUCCESS = 'ALL_PROFILE_SUCCESS'
export const ALL_PROFILE_FAIL = 'ALL_PROFILE_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'